### PR TITLE
Migrate to GitHub actions

### LINKED ISSUE #8: TODO: Migrate off of Travis CI to GitHub Actions
We need to migrate this, and all of our repositories, to GitHub Actions.

This will fix #6.

### PR DESCRIPTION
**Pull request by winem**
This PR runs lint, integration and unit tests in GitHub Actions and removes Travis. 

close #8

### CODE REVIEW

**Comment by cognifloyd** [comment]
Shall we drop py2.7 in a follow up PR?

**Comment by cognifloyd** [comment]
From reading, this looks good. We just need to enable GHA on the repo so wet can make sure it ruins to completion.

**Comment by winem** [comment]
Dropping py2.7 sounds good to me!

As far as I see, the Actions don't need to be enabled. At the moment, the workflow just exists in my forked repository and it was successful for the last commits: https://github.com/winem/st2-auth-backend-vault/actions

As soon as we merge the PR the .github/workflows/ci.yaml will exist in this repository, too, and the GHA will be executed.

I'd take care of any issues with the GHA after merging but I'm quite confident that there won't be any issues.

**Review by cognifloyd — APPROVED** [review]
LGTM

**Review by arm4b — APPROVED** [review]
Thanks for the migration!

**Pull request merged**
